name: CI_Run_tx2s3

on:
  pull_request:
    branches:
    - master_off
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch:

jobs:
  secrets:
    runs-on: ubuntu-latest
    outputs:
      available: ${{ steps.secrets.available }}
    steps:
    - name: "Configure workflow"
      id: secrets
      run: |
        DO_RUN='true'
        if [ -z "${{ secrets.TRANSIFEX_USER }}" ]; then DO_RUN='false'; fi
        if [ -z "${{ secrets.TRANSIFEX_PASSWORD }}" ]; then DO_RUN='false'; fi
        if [ -z "${{ secrets.S3_KEY }}" ]; then DO_RUN='false'; fi
        if [ -z "${{ secrets.S3_SECRET }}" ]; then DO_RUN='false'; fi

        if [ $DO_RUN == 'false' ]; then
          echo "not set credentials, not possible run"
        fi  
        echo "DO_RUN: $DO_RUN"
        echo "::set-output name=available::$DO_RUN"

  tx2s3:
    needs: secrets
    if: needs.secrets.available
    runs-on: ubuntu-18.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        sudo bash ./build/ci/tx2s3/setup.sh --tx_user ${{ secrets.TRANSIFEX_USER }} --tx_password ${{ secrets.TRANSIFEX_PASSWORD }} --s3_key ${{ secrets.S3_KEY }} --s3_secret ${{ secrets.S3_SECRET }}
    
    - name: Run tx2s3
      run: |
        sudo bash ./build/ci/tx2s3/tx2s3.sh
        
    - name: Upload artifacts on GitHub
      uses: actions/upload-artifact@v2
      with:
        name: MuseScore_locale_${{ github.run_id }}
        path: ./share/locale
  tx2s3_mu3:
    runs-on: ubuntu-18.04
    if: needs.secrets.available
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: 3.x

    - name: Setup environment
      run: |
        sudo bash ./build/ci/tx2s3/setup.sh --tx_user ${{ secrets.TRANSIFEX_USER }} --tx_password ${{ secrets.TRANSIFEX_PASSWORD }} --s3_key ${{ secrets.S3_KEY }} --s3_secret ${{ secrets.S3_SECRET }}
    
    - name: Run tx2s3
      run: |
        sudo bash ./build/ci/tx2s3/tx2s3.sh
        
    - name: Upload artifacts on GitHub
      uses: actions/upload-artifact@v2
      with:
        name: MuseScore_MU3_locale_${{ github.run_id }}
        path: ./share/locale        
